### PR TITLE
Run go mod tidy

### PR DESCRIPTION
**Pull request by Moulick**
### Description of your changes

1. It looks like the go.sum is very bloated due to missing cleanup. All I have done is run `go mod tidy` to remove unused dependencies. This is generally a good practice and results in faster downloads/less cache. 

2. Also added config to renovate to instruct it to do the `go mod tidy` whenever it upgrades a dependency.
3. Add a check in lint to catch future missing cleanup

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `go test ./...`
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Comment by Moulick** [comment]
Also, if accepted, I would be happy to make the same PR at-least for all other functions  :)

**Comment by ezgidemirel** [comment]
Thanks @Moulick for the PR! do you mind rebasing it to resolve conflicts and rerunning `go mod tidy`?

**Comment by Moulick** [comment]
@ezgidemirel Rebased! Please approve running the workflow. 

Looks like #107 did the major cleanup that this PR was doing originally. Still, this PR should prevent further bloat.

**Review by jeanduplessis — APPROVED** [review]

**Comment by jbw976** [comment]
@Moulick this is very nice addition to keeping the repo dependencies neat and tidy! 

What do you think of adding this functionality to the template repo that folks start new golang based functions projects from?
https://github.com/crossplane/function-template-go/blob/main/.github/workflows/ci.yml

Not sure if there's something equivalent for Python too 🤔 
https://github.com/crossplane/function-template-python/blob/main/.github/workflows/ci.yml

**Comment by Moulick** [comment]
The function-template-go is going to be my next stop, I'll make a PR for that soon.

I dunno anything about python¯\\\_(ツ)_/¯

**Pull request merged**
